package notification

var phrases = []string{
	"Stay hydrated, stay healthy: Regular water intake supports optimal bodily functions.",
	"Hydration boosts productivity: Keep your mind sharp and focused with frequent sips of water.",
	"Water fuels your workouts: Maintain peak performance by drinking water throughout exercise.",
	"Prevent dehydration headaches: Sip water regularly to stave off those painful headaches.",
	"Enhance skin radiance: Hydration from within promotes a glowing complexion.",
	"Support digestion: Drinking water at intervals aids in smooth digestion and prevents constipation.",
	"Beat fatigue naturally: Combat tiredness by hydrating consistently throughout the day.",
	"Regulate body temperature: Water helps regulate your internal thermostat, keeping you comfortable.",
	"Flush out toxins: Regular water intake supports your body's natural detoxification processes.",
	"Boost immunity: Proper hydration strengthens your immune system, helping you fight off illnesses more effectively.",
	"Hydrate for heart health: Water consumption supports cardiovascular function.",
	"Maintain kidney function: Regular hydration helps prevent kidney stones and supports kidney health.",
	"Stay alert and focused: Keep your mind sharp by staying hydrated throughout the day.",
	"Improve joint mobility: Drinking water regularly lubricates joints and reduces stiffness.",
	"Prevent muscle cramps: Adequate hydration minimizes the risk of painful muscle cramps.",
	"Reduce the risk of urinary tract infections: Hydration flushes out bacteria and supports urinary tract health.",
	"Enhance nutrient absorption: Water aids in the absorption of essential nutrients from food.",
	"Support weight management: Drinking water at intervals can help control appetite and prevent overeating.",
	"Boost mood and reduce stress: Proper hydration contributes to a balanced mood and stress management.",
	"Promote healthy hair growth: Hydration from within nourishes the scalp and supports hair growth.",
	"Maintain electrolyte balance: Regular water intake helps regulate electrolyte levels in the body.",
	"Improve oral health: Hydration keeps saliva flowing, which helps wash away food particles and bacteria, reducing the risk of cavities.",
	"Enhance athletic performance: Proper hydration is crucial for endurance and stamina during physical activities.",
	"Aid in recovery: Hydration supports the body's ability to recover from illness or intense exercise.",
	"Support healthy aging: Drinking water regularly can help maintain cognitive function and overall vitality as you age.",
	"Boost metabolism: Hydration plays a role in efficient metabolism and calorie burning.",
	"Prevent dry, itchy eyes: Drinking water helps keep your eyes hydrated and reduces discomfort.",
	"Enhance sleep quality: Staying hydrated can contribute to better sleep by reducing the likelihood of nighttime awakenings due to thirst.",
	"Reduce the risk of heat-related illnesses: Proper hydration is essential for staying cool and preventing heat exhaustion or heat stroke, especially in hot climates or during physical exertion.",
	"Promote overall well-being: Regular hydration is a fundamental aspect of maintaining optimal health and vitality.",
}
